@startuml
abstract class AbstractShape {
    + {abstract} ToSvg() : string
}
class Canvas {
    - Width : int
    - Height : int
    + Canvas(width:int, height:int)
    + Canvas(shapes:List<AbstractShape>, width:int, height:int)
    - BoilerSVG : string
    + AddShape(shape:AbstractShape) : void
    + getShapes() : List<AbstractShape>
    + setCanvas(l:List<AbstractShape>) : void
    + clearCanvas() : void
    + ToSvg() : string
    + {static} <<async>> SaveFile(text:string) : Task
}
class "List`1"<T> {
}
Canvas --> "Shapes<AbstractShape>" "List`1"
@enduml
